### ISSUE TITLE
Support python 3.11 for komodo on rhel8

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ecalc#423]
Komodo will switch to python 3.11 as python 3.8 is soon deprecated, and already not supported by numpy. It would be great if you added testing of libecalc against python 3.11 as well as python 3.8 . Python 3.8 will be supported for some time yet.

`pip check` in our python 3.11 komodo builds run into the following problem:

```
libecalc 8.11.0 has requirement numpy<1.25.0,>=1.24.0, but you have numpy 1.26.4.
libecalc 8.11.0 has requirement pandas<2,>=1, but you have pandas 2.2.1.
```

Note that in the period when both python 3.8 and python 3.11 is supported, there will also be a need to support both pandas 1 and pandas 2.

**Comment by TeeeJay** [comment]
Thanks for heads up, we have been waiting for it :)

**Comment by TeeeJay** [comment]
Pandas v1 and v2 are now supported for Python 3.8 and 3.11 respecively (added test for 3.9). Tests for 3.11 and numpy > 1.26 support coming very soon :)

**Comment by eivindjahren** [comment]
Eagerly waiting a PR to https://github.com/equinor/komodo-releases :)

**Comment by TeeeJay** [comment]
With #475 eCalc should now properly support all versions through 3.8 to 3.11, with testing strategy added, and parallell version support where needed.

**Comment by TeeeJay** [comment]
The changes are currently only on bleeding/main.
