### ISSUE TITLE
Add support for Pandas >= 2.0

### ISSUE THREAD

**Issue by andreas-el** [equinor/ecalc#480]
Pandas is currently pinned in pyproject.toml:

```
pandas = "^1" # due to Komodo compatibility
```
As far as I can tell, komodo installs pandas based on two repositories, in which this is one of them.

This project is one of the very few left that does not support pandas versions >= 2.0
Relates to https://github.com/equinor/webviz-subsurface/issues/1288

**Comment by TeeeJay** [comment]
@andreas-el Is it wanted to support pandas v2 with python 3.8, or only > 3.8 (3.9 and above)?

**Comment by andreas-el** [comment]
@TeeeJay We need you to add pandas v2 support for both python versions 3.8 & 3.11, as these are the versions we need to support in komodo. We are closing in on moving onto RHEL8 for komodo, which supports both these selected python versions. Once that happens, the move from python 3.8 to 3.11 will commence.
Testing have already begun on 3.11, and this (pandas version in ecalc) is one of the very few blockers left.

**Comment by TeeeJay** [comment]
@andreas-el thank you. Do we need to support both pandas v1 and v2?

**Comment by TeeeJay** [comment]
wip: https://github.com/equinor/ecalc/pull/481

**Comment by andreas-el** [comment]
> @andreas-el thank you. Do we need to support both pandas v1 and v2?

Yes. By only supporting one version, you inhibit quite the limitation on the users of komodo.

**Comment by TeeeJay** [comment]
@andreas-el does this look good for you: https://github.com/equinor/ecalc/pull/481 ?

**Comment by andreas-el** [comment]
> @andreas-el does this look good for you: #481 ?

Splendid. 🎉
