### ISSUE TITLE
eCalc does not support newer versions of scipy

### ISSUE THREAD

**Issue by andreas-el** [equinor/ecalc#602]
We are trying to keep the python 3.11 komodo build up to date, but the newer scipy-packages are incompatible with eCalc it seems.

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
libecalc 8.21.0 requires scipy<1.14,>=1.12; python_version >= "3.9", but you have scipy 1.14.1 which is incompatible.
```

**Comment by TeeeJay** [comment]
This is now supported in bleeding (main) and 8.20.4 package (next 8.20.x release to Komodo)

**Comment by TeeeJay** [comment]
Added here: https://github.com/equinor/ecalc/commit/e24df7e77f2eb64f19f9dac301d2844ad7aba996 and here https://github.com/equinor/ecalc/commit/17471caabf00caac7ac94f7730c70c94926f0094

**Comment by andreas-el** [comment]
https://github.com/equinor/komodo-releases/pull/6277
